version: "3.8"

services:
      
  user-mgmt-db:
    image: postgres:alpine
    container_name: user-mgmt-db
    ports:
      - "5010:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./user-mgmt-db:/var/lib/postgresql/data
    networks:
      app-net: {}

networks:
  app-net:
    external: true
    name: "belajar-net"
