version: "3.8"

services:
      
  task-mgr-net:
    image: postgres:alpine
    container_name: task-mgr-net
    ports:
      - "5010:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./task-mgr-net:/var/lib/postgresql/data
    networks:
      app-net: {}

networks:
  app-net:
    external: true
    name: "task-mgr-net"
